In [46]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('camada_prata/eyac2_clean.csv', delimiter = ',')

,Date,Datetime,Open,High,Low,Close,Volume
0,2010-01-04,2010-01-04 16:56:00,37.567621,37.937621,37.437621,37.937621,13303743.87
1,2010-01-05,2010-01-05 16:56:00,38.154220,38.204220,37.574220,37.774220,21396519.48
2,2010-01-06,2010-01-06 16:56:00,38.105357,38.805357,38.105357,38.805357,18720547.15
3,2010-01-07,2010-01-07 16:56:00,36.545929,36.725929,36.345929,36.425929,10964646.19
4,2010-01-08,2010-01-08 16:56:00,35.247787,35.477787,34.947787,35.037787,14624078.31
...,...,...,...,...,...,...,...
3647,2024-12-20,2024-12-20 16:56:00,39.155595,39.345595,38.705595,38.845595,59277431.74
3648,2024-12-23,2024-12-23 16:56:00,39.460157,39.510157,39.180157,39.320157,43785532.81
3649,2024-12-26,2024-12-26 16:56:00,37.727609,38.097609,37.697609,37.867609,22920777.53
3650,2024-12-27,2024-12-27 16:56:00,36.406818,36.406818,36.016818,36.066818,24167282.36
3651,2024-12-30,2024-12-30 16:56:00,36.204223,36.794223,36.194223,36.614223,22355586.67

In [48]:
df2 = pd.read_csv('camada_prata/Crude_Oil_clean.csv', delimiter = ',')

display(df2)

          Date  Price   Open   High    Low  Volume Change %
0   2024-12-31  71.25  70.69  71.52  70.43   63.63    1.02%
1   2024-12-30  70.53  70.00  71.05  69.75   93.10    0.50%
2   2024-12-27  70.18  69.27  70.32  69.06   79.13    1.37%
3   2024-12-26  69.23  69.72  70.25  68.94   69.64   -0.59%
4   2024-12-24  69.64  69.04  69.94  68.95   40.39    1.21%
5   2024-12-23  68.81  68.97  69.50  68.22   90.95   -0.30%
6   2024-12-20  69.02  68.83  69.38  68.05  114.62   -0.52%
7   2024-12-19  69.38  69.60  70.58  69.10  291.66   -0.91%
8   2024-12-18  70.02  69.82  70.80  69.39  326.61    0.53%
9   2024-12-17  69.65  70.23  70.54  68.81  280.90   -0.91%
10  2024-12-16  70.29  71.00  71.00  69.98  210.75   -0.75%
11  2024-12-13  70.82  69.64  70.94  69.51  201.26    1.67%
12  2024-12-12  69.66  69.97  70.27  68.74  231.02   -0.30%
13  2024-12-11  69.87  68.15  70.08  68.12  231.68    2.34%
14  2024-12-10  68.27  67.86  68.72  67.45  157.46    0.26%
15  2024-12-09  68.09  66.93  68.59  66.85  176.71    1.66%
16  2024-12-06  66.98  68.08  68.13  66.71  207.12   -1.44%
17  2024-12-05  67.96  68.38  68.77  67.66  129.14   -0.34%
18  2024-12-04  68.19  69.58  70.11  68.14  141.67   -1.94%
19  2024-12-03  69.54  67.89  69.83  67.65  134.42    2.51%
20  2024-12-02  67.84  67.77  68.83  67.44   95.00    0.18%
21  2024-11-29  67.72  68.39  69.32  67.60  106.39   -0.92%
22  2024-11-27  68.35  68.57  69.01  67.81   87.85   -0.13%
23  2024-11-26  68.44  68.70  69.91  67.73   98.59   -0.20%
24  2024-11-25  68.58  70.96  70.96  68.36  146.70   -3.09%
25  2024-11-22  70.77  69.85  71.02  68.96  209.42    1.43%
26  2024-11-21  69.77  68.83  70.09  68.62  131.44    1.48%
27  2024-11-20  68.75  69.28  69.96  68.64  235.64   -0.71%
28  2024-11-19  69.24  69.08  69.74  68.48  349.70    0.10%
29  2024-11-18  69.17  66.77  69.37  66.53  300.55    3.36%

In [49]:
df3 = pd.read_excel('camada_prata/ibovespa_clean.xlsx')

display(df3)

            Date  Dia       MÃªs   Ano      Valor
0     2010-02-01    1  February  2010   66571.74
1     2010-03-01    1     March  2010   67227.93
2     2010-04-01    1     April  2010   71136.34
3     2010-06-01    1      June  2010   61840.99
4     2010-07-01    1      July  2010   61236.20
...          ...  ...       ...   ...        ...
3712  2024-12-30   30  December  2024  120283.40
3713  2024-01-31   31   January  2024  127752.28
3714  2024-05-31   31       May  2024  122098.09
3715  2024-07-31   31      July  2024  127651.81
3716  2024-10-31   31   October  2024  129713.33

[3717 rows x 5 columns]

In [50]:
df_merge1 = df1.merge(df2, left_on= "Date", right_on= "Date", suffixes= ("_EYAC2", "_Petro"))

display(df_merge1)

,Date,Datetime,Open_EYAC2,High_EYAC2,Low_EYAC2,Close,Volume_EYAC2,Price,Open_Petro,High_Petro,Low_Petro,Volume_Petro,Change %
0,2024-11-18,2024-11-18 16:56:00,39.563235,40.663235,39.563235,40.563235,39004120.25,69.17,66.77,69.37,66.53,300.55,3.36%
1,2024-11-19,2024-11-19 16:56:00,36.222679,36.422679,35.772679,35.922679,26002743.35,69.24,69.08,69.74,68.48,349.70,0.10%
2,2024-11-21,2024-11-21 16:56:00,40.295113,40.455112,39.875113,40.235112,36048374.50,69.77,68.83,70.09,68.62,131.44,1.48%
3,2024-11-22,2024-11-22 16:56:00,41.044664,42.164664,40.804664,41.754664,85235103.32,70.77,69.85,71.02,68.96,209.42,1.43%
4,2024-11-25,2024-11-25 16:56:00,39.739308,40.219308,39.509308,39.539308,41119514.58,68.58,70.96,70.96,68.36,146.70,-3.09%
5,2024-11-26,2024-11-26 16:56:00,39.504093,39.654093,39.204093,39.274093,35187852.99,68.44,68.70,69.91,67.73,98.59,-0.20%
6,2024-11-27,2024-11-27 16:56:00,35.570416,35.730416,35.120416,35.360416,30600505.63,68.35,68.57,69.01,67.81,87.85,-0.13%
7,2024-11-29,2024-11-29 16:56:00,38.299903,39.019903,38.209903,38.699903,44011586.42,67.72,68.39,69.32,67.60,106.39,-0.92%
8,2024-12-02,2024-12-02 16:56:00,38.091936,38.591936,37.961936,38.341936,31711792.96,67.84,67.77,68.83,67.44,95.00,0.18%
9,2024-12-03,2024-12-03 16:56:00,37.215416,37.315416,36.895416,37.315416,22536263.38,69.54,67.89,69.83,67.65,134.42,2.51%
10,2024-12-04,2024-12-04 16:56:00,40.998943,41.358943,40.478943,40.748943,31584571.56,68.19,69.58,70.11,68.14,141.67,-1.94%
11,2024-12-05,2024-12-05 16:56:00,40.412972,40.832972,40.232972,40.662972,25214023.95,67.96,68.38,68.77,67.66,129.14,-0.34%
12,2024-12-06,2024-12-06 16:56:00,38.641859,38.701859,37.961859,38.031859,31118420.09,66.98,68.08,68.13,66.71,207.12,-1.44%
13,2024-12-09,2024-12-09 16:56:00,39.572028,40.362028,39.552028,40.232028,28548644.46,68.09,66.93,68.59,66.85,176.71,1.66%
14,2024-12-10,2024-12-10 16:56:00,39.145292,39.275292,38.955292,39.035292,21837632.54,68.27,67.86,68.72,67.45,157.46,0.26%
15,2024-12-11,2024-12-11 16:56:00,40.772756,41.182756,40.372756,41.012756,46901170.08,69.87,68.15,70.08,68.12,231.68,2.34%
16,2024-12-12,2024-12-12 16:56:00,38.724346,38.894346,38.124346,38.344346,38310786.10,69.66,69.97,70.27,68.74,231.02,-0.30%
17,2024-12-13,2024-12-13 16:56:00,36.258705,36.388705,35.578705,35.758705,23235676.19,70.82,69.64,70.94,69.51,201.26,1.67%
18,2024-12-16,2024-12-16 16:56:00,37.822001,37.892001,37.462001,37.572001,21349511.12,70.29,71.00,71.00,69.98,210.75,-0.75%
19,2024-12-17,2024-12-17 16:56:00,34.226871,34.776871,34.116871,34.586871,39617276.17,69.65,70.23,70.54,68.81,280.90,-0.91%
20,2024-12-18,2024-12-18 16:56:00,36.950543,37.070543,35.980543,35.980543,58126431.30,70.02,69.82,70.80,69.39,326.61,0.53%
21,2024-12-19,2024-12-19 16:56:00,36.679398,36.949398,35.999398,36.179398,43268468.40,69.38,69.60,70.58,69.10,291.66,-0.91%
22,2024-12-20,2024-12-20 16:56:00,39.155595,39.345595,38.705595,38.845595,59277431.74,69.02,68.83,69.38,68.05,114.62,-0.52%
23,2024-12-23,2024-12-23 16:56:00,39.460157,39.510157,39.180157,39.320157,43785532.81,68.81,68.97,69.50,68.22,90.95,-0.30%
24,2024-12-26,2024-12-26 16:56:00,37.727609,38.097609,37.697609,37.867609,22920777.53,69.23,69.72,70.25,68.94,69.64,-0.59%
25,2024-12-27,2024-12-27 16:56:00,36.406818,36.406818,36.016818,36.066818,24167282.36,70.18,69.27,70.32,69.06,79.13,1.37%
26,2024-12-30,2024-12-30 16:56:00,36.204223,36.794223,36.194223,36.614223,22355586.67,70.53,70.00,71.05,69.75,93.10,0.50%

In [54]:
df_merge2 = df_merge1.merge(df3, left_on= "Date", right_on= "Date", suffixes= ("","_Ibovespa"))

df_merge2.head()

,Date,Datetime,Open_EYAC2,High_EYAC2,Low_EYAC2,Close,Volume_EYAC2,Price,Open_Petro,High_Petro,Low_Petro,Volume_Petro,Change %,Dia,MÃªs,Ano,Valor
0,2024-11-18,2024-11-18 16:56:00,39.563235,40.663235,39.563235,40.563235,39004120.25,69.17,66.77,69.37,66.53,300.55,3.36%,18,November,2024,127768.19
1,2024-11-19,2024-11-19 16:56:00,36.222679,36.422679,35.772679,35.922679,26002743.35,69.24,69.08,69.74,68.48,349.70,0.10%,19,November,2024,128197.25
2,2024-11-21,2024-11-21 16:56:00,40.295113,40.455112,39.875113,40.235112,36048374.50,69.77,68.83,70.09,68.62,131.44,1.48%,21,November,2024,126922.11
3,2024-11-22,2024-11-22 16:56:00,41.044664,42.164664,40.804664,41.754664,85235103.32,70.77,69.85,71.02,68.96,209.42,1.43%,22,November,2024,129125.51
4,2024-11-25,2024-11-25 16:56:00,39.739308,40.219308,39.509308,39.539308,41119514.58,68.58,70.96,70.96,68.36,146.70,-3.09%,25,November,2024,129036.10

In [58]:
df_merge2 = df_merge2.rename(columns={"Close":"Close_EYAC2","Price":"Price_EYAC2",
                              "Dia":"Day_Ibovespa","Change %":"Change%_EYAC2",
                              "MÃªs":"Month_Ibovespa", "Ano":"Year_Ibovespa", "Valor":"Value_Ibovespa"})

df_merge2.head()

,Date,Datetime,Open_EYAC2,High_EYAC2,Low_EYAC2,Close_EYAC2,Volume_EYAC2,Price_EYAC2,Open_Petro,High_Petro,Low_Petro,Volume_Petro,Change %_EYAC2,Day_Ibovespa,Month_Ibovespa,Year_Ibovespa,Value_Ibovespa
0,2024-11-18,2024-11-18 16:56:00,39.563235,40.663235,39.563235,40.563235,39004120.25,69.17,66.77,69.37,66.53,300.55,3.36%,18,November,2024,127768.19
1,2024-11-19,2024-11-19 16:56:00,36.222679,36.422679,35.772679,35.922679,26002743.35,69.24,69.08,69.74,68.48,349.70,0.10%,19,November,2024,128197.25
2,2024-11-21,2024-11-21 16:56:00,40.295113,40.455112,39.875113,40.235112,36048374.50,69.77,68.83,70.09,68.62,131.44,1.48%,21,November,2024,126922.11
3,2024-11-22,2024-11-22 16:56:00,41.044664,42.164664,40.804664,41.754664,85235103.32,70.77,69.85,71.02,68.96,209.42,1.43%,22,November,2024,129125.51
4,2024-11-25,2024-11-25 16:56:00,39.739308,40.219308,39.509308,39.539308,41119514.58,68.58,70.96,70.96,68.36,146.70,-3.09%,25,November,2024,129036.10

In [60]:
df_merge2.to_csv('camada_ouro/Join_dataframes.csv')